### ISSUE TITLE
Optimize Native Token Unwraps

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#1496]
Based on an idea to save gas costs, this change ultimately reduces the number of unwrap interactions executed in batch settlements.

### Background

This [Dune Query](https://dune.xyz/queries/304513) shows the total amount of ETH spent on unwraps. Compared with our overall costs this is approximately 3% of the all time.

Up until now, there has not been a single batch containing ETH as the buy token in which we did not unwrap WETH, which suggests that there is no logic in the driver code (as of yet) to use internal balances. Here is a [dune query](https://dune.xyz/queries/307139) showing all the trades buying ETH contained inside a batch which does not include an unwrap interaction (this can be used to monitor the effect of the change once it has been implemented).

To achieve this, we will break the task into three independent sub task, each of which having a small impact on the end result. Essentially take the total unwrap amount at settlement time, compare it with the contract's ETH balance, if it decides it needs to unwrap, then it unwraps ~60% of its WETH balance into so to ensure it doesn’t have to unwrap again for a while.

### Task Breakdown

1.  [ ] Add logic in the settlement submission that is aware of the settlement contract's native ETH balance and excludes the unwrap interaction from encoded settlement whenever sufficient to settle trades involved. This change would be effective on its own by simply "topping up" the settlement contract with ETH balance, so we would immediately see results in the query above and start saving gas. This is, however a manual process of sending ETH to the contract that we would like to avoid.
2. [ ] Rework the internal buffer logic to incorporate ETH as a supported token.
3. [ ] In the third, and final step we would like to eliminate the manual process of sending ETH into the contract by making the driver aware of both its WETH and ETH balances and unwrap more than necessary when necessary to, essentially, be responsible for topping up its own ETH balances. It was suggested by Martin K. to unwrap 60% of the total WETH balance whenever unwraps are warranted. In reality we will have to unwrap at least

```js
MAX(
    ETH needed to settle the batch, 
    0.6 * (settlement contract WETH balance + amount of WETH being purchased from DEXES in the current batch)
)
```

Note that in the third step, we must take special care and account more than just the contract's internal balances, but also the WETH that winds up being purchased within the settlement itself. 

### Example of weird scenario
For example, consider a batch containing a trade buying 2 ETH. The settlement contract has 1 WETH and 0 ETH. This implies we will have to make a dex interaction to settle the trade (buying 2 ETH), we would then have 3 WETH, but we need to unwrap at least 2 to settle the trade (i.e. more than 60%).

There is already an old open PR #1313 containing additional discussion on the topic that I will now close in favour of this well defined three task issue description. The only valuable code there at this point that could be recycled is the following block for WETH/ETH balance fetching

```rs
pub async fn get_eth_weth_balance(web3: &Web3, address: H160) -> Result<(U256, U256)> {
    let weth = WETH9::deployed(web3).await?;
    // TODO - fetch the next two in parallel
    let weth_balance = weth.methods().balance_of(address).call().await?;
    let native_asset_balance = &web3.eth().balance(address, None).await?;
    Ok((weth_balance, native_asset_balance.into()))
}
```

Note that the weth and eth balances can be fetched in parallel.

**Comment by nlordell** [comment]
A couple of notes:
- I would start with the following since it would already have a pretty decent impact and fix something we already have
  > Rework the internal buffer logic to incorporate ETH as a supported token.
- I would make the ratio that we unwrap configurable (not fixed at 60%).

For @MartinquaXD a little more context around the first point:

The settlement contract collects fees from orders by transferring `sellAmount + feeAmount` in, but only converting `sellAmount` to some `buyAmount` to transfer out. This means that for every trade, we transfer a bit more `sellToken` in than we actually trade (our fees). Over time, these grow and we have what we call "settlement contract buffers". Typically, if a settlement trades tokens `X` -> `Y`, we will transfer `sellAmount + feeAmount` of `X` in, trade `sellAmount` of `X` for `Y` against some on-chain AMM and then transfer the traded `buyAmount` out to the user. As an optimization, when a settlement comes in that trades tokens that we trust (for example `USDT->WETH`) and we have enough `WETH` accumulated in these buffers to cover the output `buyAmount` we will just send the `buyAmount` from this internal balance and not trade against any AMM (this saves a TON of gas). This same logic should also work for ETH (something we have to verify and fix if it doesn't).

**Comment by bh2smith** [comment]
Here are some [basic results](https://dune.xyz/queries/309418) that tell us how many unwraps would have been avoided if we had maintained an ETH balance of X: A sample table of results


|ETH balance |  %avoided|
|---:|---|
|1 |  66 |
|2 |  77 |
|3 |  82 |
|4 |  85 |
|5 |  87 |
|6 |  89 |
|7 |  90 |
|8 |  91 |
|9 |  92 |
|10 | 92 |
|20 | 96 |
|30 | 97 |
|40 | 98 |
