### ISSUE TITLE
Implement optimized native price estimation

### ISSUE THREAD

**Issue by MartinquaXD** [gnosis/gp-v2-services#1615]
#1582 collected some ideas and requirements how to optimize the native token price calculation. This issue reiterates once more the requirements and presents concrete implementation ideas to achieve them.

1. We need a component optimized to calculate a tokens' price in terms of the native token (ETH, xDai)
2. Make use of existing `PriceEstimators` by being compatible with the `PriceEstimating` trait
3. It should utilize a cache to keep latency low
4. This cache needs to stay up-to-date by doing maintenance periodically (similar to `solvable_orders`)
5. The code needs to be shareable with the planned `/auction` endpoint

### Idea
Use existing PriceEstimators to compose a second estimator hierarchy which is optimized for caching native token price queries. To be able to maintain the native price cache in the background, a new type will be implemented which holds a `Weak<CachingPriceEstimator>` that will refetch token prices periodically triggered by `ServiceMaintenance`.
This way the requirements can be met without introducing too much new code while still having the option to easily switch out the implementation later on.

### Roadmap
- [ ] Implement `NativePriceEstimating` trait for all types implementing `PriceEstimating`
- [ ] Refactor existing price estimator code a bit
  - [ ] Make `SantitizedPriceEstimator` store a `Arc<dyn PriceEstimating>` instead of `T: PriceEstimating` (this is needed to create a second price estimator hierarchy specialized for native token price estimation)
  - [ ] Add helper fn in `/orderbook/src/main.rs` which instantiates PriceEstimators based on `&[PriceEstimatorType]` (this makes it possible to create an entirely separate estimator hierarchy with minimal code duplication)
- [ ] Update `MinFeeCalculator::compute_unsubsidized_min_fee` to use optimized price estimator
  - [ ] Create new estimator hierarchy `SanitizedPE` -> `CachingPE` -> `CompetitionPE`
  - [ ] Store new estimator in `MinFeeCalculator`
  - [ ] Use new estimator in `compute_unsubsidized_min_fee`
- [ ] Maintain cache for native token prices
  - [ ] Implement `PriceCacheMaintainer` which implements `Maintaining` and manages a `CachingPE`
  - [ ] Instantiate `PriceCacheMaintainer` for the `CachingPE` inside the native price estimator hierarchy and pass that to `ServiceMaintenance`

### The new `NativePriceEstimating` trait
```rust
#[mockall::automock]
#[async_trait::async_trait]
pub trait NativePriceEstimating: Send + Sync {
    async fn native_price(
        &self,
        token: &H160,
        native_token: &H160,
        sell_amount: &U256,
    ) -> Result<f64, PriceEstimationError> {
        self.native_prices(std::slice::from_ref(token), native_token, sell_amount)
            .await
            .into_iter()
            .next()
            .unwrap()
    }

    /// Returns one result for each query.
    async fn native_prices(
        &self,
        tokens: &[H160],
        native_token: &H160,
        sell_amount: &U256,
    ) -> Vec<Result<f64, PriceEstimationError>>;
}

#[async_trait::async_trait]
impl<T> NativePriceEstimating for T
where
    T: PriceEstimating,
{
    async fn native_prices(
        &self,
        tokens: &[H160],
        native_token: &H160,
        sell_amount: &U256,
    ) -> Vec<Result<f64, PriceEstimationError>> {
        let native_token_queries: Vec<_> = tokens
            .iter()
            .map(|token| Query {
                sell_token: *token,
                buy_token: *native_token,
                in_amount: *sell_amount,
                kind: OrderKind::Buy,
            })
            .collect();

        let estimates = self.estimates(&native_token_queries).await;

        estimates
            .into_iter()
            .zip(native_token_queries.iter())
            .map(|(estimate, query)| {
                estimate.map(|estimate| estimate.price_in_sell_token_f64(query))
            })
            .collect()
    }
}
```

### Maintaining the native price cache
```rust
pub struct PriceCacheMaintainer {
    estimator: Weak<CachingPriceEstimator>,
}

impl PriceCacheMaintainer {
    pub fn new(estimator: &Arc<CachingPriceEstimator>) -> Self {
        Self {
            estimator: Arc::downgrade(estimator),
        }
    }
}

#[async_trait::async_trait]
impl Maintaining for PriceCacheMaintainer {
    async fn run_maintenance(&self) -> anyhow::Result<()> {
        let estimator = match self.estimator.upgrade() {
            Some(estimator) => estimator,
            None => return Err(anyhow::anyhow!("estimator already freed")),
        };

        let queries: Vec<_> = estimator
            .cache
            .lock()
            .unwrap()
            .key_order()
            .cloned()
            .collect();
        let estimates = estimator.estimates(&queries).await;
        let queries_and_estimates = queries.iter().zip(estimates.into_iter());
        {
            let mut cache = estimator.cache.lock().unwrap();
            for (query, estimate) in queries_and_estimates {
                if let Ok(estimate) = estimate {
                    cache.cache_set(*query, estimate);
                }
            }
        }
        Ok(())
    }
}
```

**Comment by MartinquaXD** [comment]
An alternative idea for `NativePriceEstimating` would be a cleaner signature like this:
```rust
async fn native_prices(&self, tokens: &[H160]) -> Vec<Result<f64, PriceEstimationError>>;
```
This would prevent having a default implementation for all `PriceEstimating` types, though. Instead one could imaging a thin wrapper around a `PriceEstimating` which would implement `NativePriceEstimating` for it instead:
```rust
struct NativePriceEstimator {
    inner: Arc<dyn PriceEstimating>,
    native_token: H160,
    amount: U256
}

impl NativePriceEstimating for NativePriceEstimator {
    //...
}
```

**Comment by vkgnosis** [comment]
I would not do

> Make use of existing PriceEstimators by being compatible with the PriceEstimating trait

because it I think it would be better to have a clean api. For native estimates the amount is not relevant and buy/sell distinction isn't either. Afaik there is only one component that needs the native price which is MinFeeCalculator. Here we can pass in the new caching native price estimator.

**Comment by vkgnosis** [comment]
The rest of the plan makes sense to me. Sorry if that wasn't clear in the previous comment.
The maintaining trait runs every new block btw which might be overkill for the native price cache. It is unfortunately named in hindsight. We can manually spawn a tokio task to do the updating. I feel it doesn't have to happen more than every 30 seconds.

We will have to decide on a strategy for which tokens to evict and which to keep (and auto update) in the cache. Could be something as simple as the last x most recently used.

**Comment by MartinquaXD** [comment]
Thanks for the feedback. I'm fine with not having the `NativePriceEstimating` trait and use `PriceEstimating` for now. I guess we will see if we actually need a more specialized trait in the future.

Because we don't trade many different tokens every batch auction, refetching the X most recently used tokens will probably be good enough for now. We might have to keep an eye on that as the number of traded tokens growth with our user base.

**Comment by vkgnosis** [comment]
To be clear I am in favor of using a special trait. I would *not* use the PriceEstimating trait for the native token price estimator interface.

**Comment by MartinquaXD** [comment]
Mmh, okay. I was confused by:
> Here we can pass in the new caching native price estimator.

Just to make sure I understand you correctly. Would you be in favor of the second approach I mentioned in my first comment? (a wrapper struct which enables us to implement cleaner function signatures for a `NativePriceEstimating` trait)
Or are you suggesting another alternative idea for which there is currently no concrete implementation proposal?

**Comment by vkgnosis** [comment]
I would like to have a component like

```rust
trait NativePriceEstimator {
    pub fn estimate_native_price(token: H160) -> Result<...>
}
```

This component would right now only be used by MinFeeCalculator. In the future it would also be used by the auction endpoint. This component can like you described internally cache native prices and update them automatically. Note that the trait is different from PriceEstimating which I think this new component should not implement.
