### ISSUE TITLE
Balancer Integration: WeightedPool Fetching

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#603]
After a few discussions about how best to fetch pools, given the options of 

- API calls to Google Big Query (for pools and reserves)
- Indexing Pool Created events and fetching reserves directly from the EVM

We have decided to go the route that does not rely on any third party service; namely, the latter.

To sketch out a plan for this, I envision that we will implement the following steps sequentially
- [x] Migrate reusable components of event handling for GPv2Settlement into shared crate - #606, #614, #613 and #616 
- [x] Setup Event Receiving (aka Streaming) For `BalancerV2Vault` contract (#641)
- [x] Implement Event Storing for Balancer events (#642).
- [x] `getNormalizedWeights` for each `WeightedPool`. (#696)
- [x] Write and Implement `WeightedPoolFetching` for `BalancerPoolFetcher` (#698)
- [ ] Read/Write Balancer Pool Registry to and from file (for more efficient cold start) - #723. This task is still undergoing debate as to the most appropriate design. We are planning to load Pool Registry from the balancer-v2 [subgraph](https://thegraph.com/explorer/subgraph/balancer-labs/balancer-v2), but also talk about being able to load from file when the graph is unavailable.
- [x] ~~Filtered Event Receiving by topic (cf issue #681)~~ no longer necessary.

Note that whenever the pools are actually needed by the services, we would have to query the reserves at the time of use (to have the most updated info) - but this is outside the scope of this task.

One thing that we may need to be careful of is that both solver and orderbook services will make use of this (one for price estimating and the other for solution finding) so we should take care to avoid data races when updating cached or dumped pool data.

**Comment by nlordell** [comment]
Looks like a very good plan! One suggestion to reduce the scope a bit:

> I would suggest implementing a simple read/write WeightedPools to and from file

This is a very good suggestion for speeding up "warm starts". I think we should leave this for last though as I suspect indexing all `WeightedPool` addresses and static data (pool ID, weights, scales, tokens, etc.) will be quick enough for now that this won't be necessary (until the number of existing pools grows substantially). I would even suggest to keep that as a separate issue for now so we can decide how much it is needed/when it is needed.

**Comment by fleupold** [comment]
Sounds great! I'm not sure how much code can be shared from the existing "event listening" part, maybe the EventStream and the "newBlockStream" can be abstracted behind a common interface to give us an automatically updating event stream (but that might be quite involved given we handle "reorgs" in the custom business logic).

> One thing that we may need to be careful about is that both solver and orderbook services will make use of this (one for price estimating and the other for solution finding) so we should take care to avoid data races when updating cached or dumped pool data.

Note, that orderbook and solver services run in different pods and while they share code they don't have access to the same memory/disk.

**Comment by bh2smith** [comment]
This was essentially concluded by #698 and polished off in the more recent #722
