### ISSUE TITLE
Balancer StablePool Integration

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#733]
The logical progression of this task is broken down into the following PRs

1. [x] Contract Artifacts #997
2. [x] Fetch Stable Pools from the Graph #1003 
3. [x] Info Fetching #1006 
4. [x] PoolRegistry and Event Handler #1007
5. [x] Refactor some terms #1008
6. [x] Pool Fetching #998 
7. [x] Forward pools to HTTP solver #992 
8. [ ] Include Stable Pools in Baseline Solver
9. [ ] Include Balancer Pools in Price Estimation Service

Just to keep track of the collected knowledge so far. The following link contains some valuable information regarding the differences between Weighted and Stable Pools when the time for integration comes:

https://github.com/gnosis/gp-v2-services/pull/717#discussion_r651684681

To elaborate a bit more on Stable Pools and how they differ from our current `WeightedPool` struct:

Stable Pools do not have weights, but they do have an `amplificationParameter` (which is not part of the weighted pools) that is passed though the methods `_onSwapGivenIn` and `_onSwapGivenOut`. This amplification parameter changes on everyblock and can be fetched via a public view method `getAmplificationParameter`. 

Specifically, these methods call into

```
StableMath._calcOutGivenIn(currentAmp, balances, indexIn, indexOut, swapRequest.amount)
```

We note that generically `getAmplificationParameter` could be evaluated from the value passed into the constructor and the current block height, but there are some manual overrides to the value so we probably shouldn't attempt to compute its current value manually.

With this in mind I propose that 

```rust
pub struct RegisteredStablePool {
    pub pool_id: H256,
    pub pool_address: H160,
    pub tokens: Vec<H160>,
    pub scaling_exponents: Vec<u8>,
    block_created: u64,
}
````

Which is essentially the same as `RegisteredWeightedPool` without the weights.

Our `PoolRegistry` Would stay similar except that We would replace the values of the `pools` hashmap with `BalancerPool` where

```
enum BalancerPool {
  Weighted(WeightedPool),
  Stable(StablePool),
}
```

The `PoolFetching`, which is responsible for getting pool reserves, would then also need to get the current Amplification value whenever it is faced with a StablePool.

**Comment by bh2smith** [comment]
I suppose this issue is outdated due to recent refactor and was essentially completed with the exception of the last task (that should have been a separate issue anyway)
