### ISSUE TITLE
Prepare Balancer Pool Data for HTTP Solver

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#769]
This task is broken down into several steps:

- [x] Remodel the `UniswapModel` for a more general `PoolModel` (#761)
- [x] Start passing Token Addresses as H160 to the solver instead of `tN` (#763) - Merged Into #761.
- [x] Rename `AmmOrder` and all instances of it for `ConstantProductOrder`(#770)
- [x] Introduce `WeightedProductOrder` and all analogous mappings similar to `ConstantProductOrder`
- [ ] Pass relevant details through to `Solver::prepare_model`
